package com.example.vant_demo_success.dataobject;

public class AaDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aa.aa
     *
     * @mbg.generated Mon Mar 16 16:10:36 CST 2020
     */
    private String aa;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aa.aa
     *
     * @return the value of aa.aa
     *
     * @mbg.generated Mon Mar 16 16:10:36 CST 2020
     */
    public String getAa() {
        return aa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aa.aa
     *
     * @param aa the value for aa.aa
     *
     * @mbg.generated Mon Mar 16 16:10:36 CST 2020
     */
    public void setAa(String aa) {
        this.aa = aa == null ? null : aa.trim();
    }
}