package com.example.vant_demo_success.dataobject;

public class GoodsListDOWithBLOBs extends GoodsListDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_list.image
     *
     * @mbg.generated Wed Mar 11 16:27:39 CST 2020
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_list.details
     *
     * @mbg.generated Wed Mar 11 16:27:39 CST 2020
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_list.image
     *
     * @return the value of goods_list.image
     *
     * @mbg.generated Wed Mar 11 16:27:39 CST 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_list.image
     *
     * @param image the value for goods_list.image
     *
     * @mbg.generated Wed Mar 11 16:27:39 CST 2020
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_list.details
     *
     * @return the value of goods_list.details
     *
     * @mbg.generated Wed Mar 11 16:27:39 CST 2020
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_list.details
     *
     * @param details the value for goods_list.details
     *
     * @mbg.generated Wed Mar 11 16:27:39 CST 2020
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }
}