package com.example.vant_demo_success.dataobject;

public class HomeDOWithBLOBs extends HomeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home.goodPrice
     *
     * @mbg.generated Wed Mar 11 12:02:22 CST 2020
     */
    private String goodprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home.headerSwipes
     *
     * @mbg.generated Wed Mar 11 12:02:22 CST 2020
     */
    private String headerswipes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home.recommends
     *
     * @mbg.generated Wed Mar 11 12:02:22 CST 2020
     */
    private String recommends;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home.goodPrice
     *
     * @return the value of home.goodPrice
     *
     * @mbg.generated Wed Mar 11 12:02:22 CST 2020
     */
    public String getGoodprice() {
        return goodprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home.goodPrice
     *
     * @param goodprice the value for home.goodPrice
     *
     * @mbg.generated Wed Mar 11 12:02:22 CST 2020
     */
    public void setGoodprice(String goodprice) {
        this.goodprice = goodprice == null ? null : goodprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home.headerSwipes
     *
     * @return the value of home.headerSwipes
     *
     * @mbg.generated Wed Mar 11 12:02:22 CST 2020
     */
    public String getHeaderswipes() {
        return headerswipes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home.headerSwipes
     *
     * @param headerswipes the value for home.headerSwipes
     *
     * @mbg.generated Wed Mar 11 12:02:22 CST 2020
     */
    public void setHeaderswipes(String headerswipes) {
        this.headerswipes = headerswipes == null ? null : headerswipes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home.recommends
     *
     * @return the value of home.recommends
     *
     * @mbg.generated Wed Mar 11 12:02:22 CST 2020
     */
    public String getRecommends() {
        return recommends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home.recommends
     *
     * @param recommends the value for home.recommends
     *
     * @mbg.generated Wed Mar 11 12:02:22 CST 2020
     */
    public void setRecommends(String recommends) {
        this.recommends = recommends == null ? null : recommends.trim();
    }
}