const baseURL = '/user'
const user = {
    loginSendCode: `${baseURL}/loginSendCode`,
    registerSendCode: `${baseURL}/registerSendCode`,
    checkRegisterCode: `${baseURL}/checkRegisterCode`,
    checkUser: `${baseURL}/checkUser`,
    insertUser: `${baseURL}/insertUser`,
    loginByAccount: `${baseURL}/loginByAccount`,
    loginByTel: `${baseURL}/loginByTel`,
    checkTel: `${baseURL}/checkTel`,
    getMessage: `${baseURL}/getMessage`,
    login: `${baseURL}/login`,
    logOut: `${baseURL}/logOut`,
    updateUserName: `${baseURL}/updateUserName`,
    updateUserSex: `${baseURL}/updateUserSex`,
    updateUserBirthday: `${baseURL}/updateUserBirthday`,
    insertAddress: `${baseURL}/insertAddress`,
    getAddressList: `${baseURL}/getAddressList`,
    updateAddress: `${baseURL}/updateAddress`,
    setUserCollects: `${baseURL}/setUserCollects`,
    getCollectList: `${baseURL}/getCollectList`,
    getCartList: `${baseURL}/getCartList`,
    setUserCart: `${baseURL}/setUserCart`,
    checkPayPwd: `${baseURL}/checkPayPwd`,
    hasPayPwd: `${baseURL}/hasPayPwd`, 
    setPayPwd: `${baseURL}/setPayPwd`, 
    checkStar: `${baseURL}/checkStar`,
    pay_success: `${baseURL}/pay_success`,
    initOrderDetail: `${baseURL}/initOrderDetail`,
    set_unassess: `${baseURL}/set_unassess`,
    getUserImg: `${baseURL}/getUserImg`,
    saveUserImg: `${baseURL}/saveUserImg`,
    updateUserImgPath: `${baseURL}/updateUserImgPath`,
    delUserImgPath: `${baseURL}/delUserImgPath`,
    getUserNameByID: `${baseURL}/getUserNameByID`,
    searchUsers: `${baseURL}/searchUsers`,
    sendByMail: `${baseURL}/sendByMail`,
    addAddress: `${baseURL}/addAddress`,
    ediAddress: `${baseURL}/ediAddress`,
    delAddress: `${baseURL}/delAddress`,
    cartAdd: `${baseURL}/cartAdd`,
    cartDel: `${baseURL}/cartDel`,
    removePro: `${baseURL}/removePro`,
    getCartItem: `${baseURL}/getCartItem`,
    cart_num_up1: `${baseURL}/cart_num_up1`,
    updateCart: `${baseURL}/updateCart`,
}
export default user