package com.example.vant_demo_success.dao;

import com.example.vant_demo_success.dataobject.AaDO;

public interface AaDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa
     *
     * @mbg.generated Mon Mar 16 16:10:37 CST 2020
     */
    int insert(AaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa
     *
     * @mbg.generated Mon Mar 16 16:10:37 CST 2020
     */
    int insertSelective(AaDO record);
}