package com.example.vant_demo_success.dao;

import com.example.vant_demo_success.dataobject.AssessDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AssessDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbg.generated Tue Apr 28 11:08:02 CST 2020
     */
    int deleteByPrimaryKey(Integer id);
    int delByUserID(@Param("userid") Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbg.generated Tue Apr 28 11:08:02 CST 2020
     */
    int insert(AssessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbg.generated Tue Apr 28 11:08:02 CST 2020
     */
    int insertSelective(AssessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbg.generated Tue Apr 28 11:08:02 CST 2020
     */
    AssessDO selectByPrimaryKey(Integer id);

    List<AssessDO> getGoodAssess(@Param("goodsid") Integer goodsid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbg.generated Tue Apr 28 11:08:02 CST 2020
     */
    int updateByPrimaryKeySelective(AssessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbg.generated Tue Apr 28 11:08:02 CST 2020
     */
    int updateByPrimaryKey(AssessDO record);
}