package com.example.vant_demo_success.dao;

import com.example.vant_demo_success.dataobject.AssessDO_old;

public interface AssessDOMapper_old {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbg.generated Mon Feb 24 15:11:34 CST 2020
     */
    int deleteByPrimaryKey(Integer goodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbg.generated Mon Feb 24 15:11:34 CST 2020
     */
    int insert(AssessDO_old record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbg.generated Mon Feb 24 15:11:34 CST 2020
     */
    int insertSelective(AssessDO_old record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbg.generated Mon Feb 24 15:11:34 CST 2020
     */
    AssessDO_old selectByPrimaryKey(Integer goodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbg.generated Mon Feb 24 15:11:34 CST 2020
     */
    int updateByPrimaryKeySelective(AssessDO_old record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess
     *
     * @mbg.generated Mon Feb 24 15:11:34 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(AssessDO_old record);
}