package com.example.vant_demo_success.dao;

import com.example.vant_demo_success.dataobject.CartDO_old2;

public interface CartDOMapper_old2 {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Tue Apr 28 15:14:47 CST 2020
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Tue Apr 28 15:14:47 CST 2020
     */
    int insert(CartDO_old2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Tue Apr 28 15:14:47 CST 2020
     */
    int insertSelective(CartDO_old2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Tue Apr 28 15:14:47 CST 2020
     */
    CartDO_old2 selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Tue Apr 28 15:14:47 CST 2020
     */
    int updateByPrimaryKeySelective(CartDO_old2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Tue Apr 28 15:14:47 CST 2020
     */
    int updateByPrimaryKey(CartDO_old2 record);
}